### ISSUE TITLE
Aqua.jl does not like comments in the `Project.toml`

### ISSUE THREAD

**Issue by bvdmitri** [JuliaTesting/Aqua.jl#100]
Currently if the `Project.toml` contains some comments the tests from `Aqua` will fail indicating that `Pkg.resolve` will change the content of the file. `Pkg.resolve`, in fact, does not care about comments in the `Project.toml` and does not change the content of the file.

**Comment by Roger-luo** [comment]
I think it's not Aqua's problem but it's because TOML is not doing an actual serializer... so it removes anything that is not a dictionary

**Comment by bvdmitri** [comment]
Well IMO the fact that Aqua uses TOML library should not really be relevant for a user. From a user perspective `Aqua` shows me some an error message saying that `Pkg.resolve` will change the content of the file, while in reality it does not. I would still say that it is Aqua's problem, because Aqua could use a different library or a different algorithm to perform this check.

**Comment by Roger-luo** [comment]
There's no other alternative TOML parser/serializer in Julia.

**Comment by bvdmitri** [comment]
What do you mean exactly by "go ahead Pkg"? I tried different things, but Pkg never removed the comments present in the file. I tried `] up`, `] resolve`, `] build`, `]  instantiate` in both local and global environments and comments are still present in my `dev`-ed version. The comments are also present in the `] add`-ed version of the package so the official package registry does not care about the comments in the `Project.toml` and does not remove them.

What exactly should I do such that `Pkg` removes the comments and why it is considered to be a bad thing after all?

**Comment by Roger-luo** [comment]
> The comments are also present in the ] add-ed version of the package so the official package registry does not care about the comments in the Project.toml and does not remove them.

I'm not sure why you don't have it, but just a simple try already produces this behavior with only Pkg.

```toml
[deps]
# jkmadkmaslkdmlkasmdlkas
```

```julia
using Pkg; Pkg.add("Example")
```

**Comment by Roger-luo** [comment]
See also https://github.com/JuliaLang/julia/issues/42697

**Comment by bvdmitri** [comment]
Thank you for sharing your thoughts on this! I read through the discussion you posted and it definitely helped me understand the issue better. From what I gather, comments in the Project.toml file are only removed when the `Project.toml` needs to be modified. In my case, since there was no need to modify the `Project.toml`, the `Pkg` did not remove the comments.

For example, it seems like even in cases where `Example` is already present in the toml, the comments won't be removed because there's no need to modify the file. Try for example:

```julia
[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
# comment
```

```julia
] add Example
```

That being said, I think it would be helpful if the error message in Aqua was more clear about when comments will be removed. Currently, it does throw an error saying that `Pkg.resolve` **will** remove the comments and this is a bit misleading. In fact any `Pkg` command can remove the comments, but only if it **needs to modify** the Project.toml.

Feel free to close the issue.

**Comment by lgoettgens** [comment]
Resolved by https://github.com/JuliaTesting/Aqua.jl/pull/122.
