### ISSUE TITLE
[Question] `Unbound type parameters`

### ISSUE THREAD

**Issue by pedroripper** [JuliaTesting/Aqua.jl#104]
Hi!

I'm getting an `Unbound type parameters` for this function:

```julia
function example(
    parameter_1::String,
    parameter_2::String,
    parameter_3::String,
    code_1::Union{T, Nothing} = nothing,
    code_2::Union{T, Nothing} = nothing,
) where {T <: Union{String, Integer}}
    println(parameter_1)
    println(parameter_2)
    println(parameter_3)
    println(code_1)
    println(code_2)

    return nothing
end
```

As I have limited T to be `String`, `Integer` or `Nothing`, could you explain why I received this error?
From what I have tested, if I remove `Nothing` , the error disappears. But I don't known the reason for that.

Thank you!

**Comment by lgoettgens** [comment]
If you call your function as `example("string1", "string2", "string3")` or `example("string1", "string2", "string3", nothing, nothing)`, julia cannot deduce the value of `T`.

**Comment by fingolfin** [comment]
Thank you for your report, @pedroripper , and thank you for the helpful analysis, @lgoettgens .


It seems this code snippet wants to enforce that if `code_1` and `code_2` are *both* not `nothing`, then they must have the same type.

I would suggest expressing this instead in code, and then add a helpful error. That's more user friendly anyway. So e.g. this:
```
function example(
    parameter_1::String,
    parameter_2::String,
    parameter_3::String,
    code_1::Union{String, Integer, Nothing} = nothing,
    code_2::Union{String, Integer, Nothing} = nothing,
)
    if !isnothing(code_1) && isnothing(code_2) and typeof(code_1) != typeof(code_1)
      error("if both code_1 and code_2 are given, they must have the same type")
    end
    println(parameter_1)
    println(parameter_2)
    println(parameter_3)
    println(code_1)
    println(code_2)

    return nothing
end
```

Anyway, Aqua is reporting a valid issue, so this is not a bug.
