### ISSUE TITLE
Check weakdeps for being stale

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#136]
> But we would also want to check for actual stale deps in the extensions too, right? So I guess the criterion is rather "is the dependency imported at all, whether in the main package or in an extension"

_Originally posted by @gdalle in https://github.com/JuliaTesting/Aqua.jl/issues/107#issuecomment-1572756617_

**Comment by lgoettgens** [comment]
After thinking about this again, I think that this is a no-op:
For a package extension, say `PkgExt`, to be available its weakdeps have to be already loaded. But then there is nothing we can check for if they are indeed imported or used in `PkgExt`.

To recall the idea behind the usual `test_stale_deps`: Load the pkg, list all pkgs that are loaded after that, and report everything in the Project.toml that has not been loaded.

@gdalle Do you have any idea on how this could work conceptually? If not, I would close this.

**Comment by gdalle** [comment]
Oh I didn't know it worked like that, in that case yeah it's tricky. Maybe add a warning to the Aqua docs saying that the deps of extensions cannot be checked?
