### ISSUE TITLE
TypePiracy: treat foreign type as own type

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#138]
Originally brought up in https://github.com/oscar-system/GAP.jl/pull/889#issuecomment-1578075249. 

The julia docu explains some scenario, where one would have a good reason to do type piracy, e. g. when splitting a C wrapper into a lightweight jll defining the types and another julia package implementing higher level functionality, see https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy-1 (last paragraph).

I would thus propose to add a kwarg to the piracy test with a list of types that should be treated as own types even if they are foreign.
Most other Aqua test cases have some kind of `ignore` kwarg, so I see no point in not having something similar for `test_piracy`.

**Comment by devmotion** [comment]
It would also be useful to be able to specify that a function is owned by a different package: For instance, StatsAPI defines function stumps that are officially declared to be owned by StatsBase - but currently Aqua flags their default implementation for generic types (defined in Base) as type piracy (https://github.com/JuliaStats/StatsBase.jl/pull/866).

**Comment by lgoettgens** [comment]
So a solution to you would be to split up my proposed kwarg `treat_as_own` into two different ones: one for types that works as proposed in #140, and one for functions, which just doesn't check type piracy for the functions given there.
Is that what you have in mind?

And I would like to hear the opinion of @fingolfin on this - If there is nothing I have missed, I will update my pr #140 to include your idea as well.

**Comment by devmotion** [comment]
Yes, I think such a generalization would fix my use case in StatsBase as well.
