### ISSUE TITLE
False positive for unbound type parameters

### ISSUE THREAD

**Issue by gdalle** [JuliaTesting/Aqua.jl#139]
Is this intended behavior?
```julia
julia> module MyPackage
       second_type(::Type{Union{A,B}}) where {A,B} = B
       end;

julia> using Aqua, .MyPackage

julia> Aqua.test_unbound_args(MyPackage)
Test Failed at /home/guillaume/.julia/packages/Aqua/2aeHf/src/unbound_args.jl:10
  Expression: detect_unbound_args_recursively(m) == []
   Evaluated: Any[second_type(::Type{Union{A, B}}) where {A, B} @ Main.MyPackage ~/Downloads/aqua_unbound.jl:2] == Any[]

ERROR: There was an error during testing
```

**Comment by lgoettgens** [comment]
I am trying to understand what your function is intended to do. Could you provide a call to `second_type` with some arguments, that does not error?

**Comment by lgoettgens** [comment]
Anyway, Aqua delegates the unbound args test to the `Test` stdlib.

```julia
julia> Test.detect_unbound_args(MyPackage; recursive=true)
[1] second_type(::Type{Union{A, B}}) where {A, B} @ Main.MyPackage REPL[24]:2
```
So this is either an upstream issue or intended.

**Comment by gdalle** [comment]
It's meant to parse the second type of a Union:
```julia
julia> second_type(::Type{Union{A,B}}) where {A,B} = B
second_type (generic function with 1 method)

julia> T = Union{Int,Float64}
Union{Float64, Int64}

julia> second_type(T)
Int64
```
And that's my point, I wasn't able to write it in a non-broken way. I'll investigate this in Test, thanks!

**Comment by fingolfin** [comment]
This signature is not valid because the order of types in a union is not well-defined. Consider `Union{Int,Bool}` -- this is identical to `Union{Bool,Int}`

**Comment by gdalle** [comment]
Oooooh that's interesting!
In that case I will gladly reveal the function is not from me, I just read it in an old pull request and I'm glad it broke Aqua :rofl:
