### ISSUE TITLE
Issue with the badge (GIF 322)

### ISSUE THREAD

**Issue by tlienart** [JuliaTesting/Aqua.jl#15]
On your ThreadsX page:

![Screen Shot 2020-03-29 at 11 16 02](https://user-images.githubusercontent.com/10897531/77845383-c913fd00-71ae-11ea-979d-1d5f01ce86df.png)

On FF it shows as "Gif 322" (screenshot), on Safari and Chromium as a square box.

Not sure if that's an issue that you could fix here?

**Comment by tkf** [comment]
Thanks for filing this issue.

It actually works in my Firefox (72.0.1):
![image](https://user-images.githubusercontent.com/29282/77857595-4b9ebb80-71b3-11ea-8190-b0dbe310666a.png)

Though I guess the point is that using not-so-famous Unicode character in the badge is not a great idea...  I guess the easiest fix is to convert this SVG to PNG locally and serve it via GitHub.
