### ISSUE TITLE
Stale deps test misses `Statistics` in `BlockBandedMatrices.jl`

### ISSUE THREAD

**Issue by jishnub** [JuliaTesting/Aqua.jl#163]
In https://github.com/JuliaLinearAlgebra/BlockBandedMatrices.jl/actions/runs/5672874507/job/15373054076, the Aqua ("project quality") test passed, but the package has `Statistics` as a stale dependency that it doesn't load. The Aqua command that it uses is
```julia
Aqua.test_all(BlockBandedMatrices, ambiguities=false, piracy=false,
        # only test formatting on VERSION >= v1.7
        # https://github.com/JuliaTesting/Aqua.jl/issues/105#issuecomment-1551405866
        project_toml_formatting = VERSION >= v"1.9")
```
so stale deps should be tested for. Oddly, this leads to a test failure in [a downstream test](https://github.com/JuliaArrays/FillArrays.jl/actions/runs/5673518008/job/15375154861?pr=286) in `FillArrays.jl` (I'm unsure if this has just been fixed).

In case it matters, one of the example files (in the `examples` directory) loads `Statistics`

**Comment by lgoettgens** [comment]
If I am not mistaken, `Statistics` is a stdlib, right?
If yes, Aqua does not guarantee to detect it not being used (see https://juliatesting.github.io/Aqua.jl/stable/#Aqua.test_stale_deps).

Nevertheless, it is weird that it behaves differently in the two different test cases. I will dig into this.

**Comment by lgoettgens** [comment]
Ok, so I have an explanation now.
In `BlockBandedMatrices.jl` before https://github.com/JuliaLinearAlgebra/BlockBandedMatrices.jl/pull/164 (so e.g. `v0.12.3`), `Statistics.jl` is not considered a stale dependency, as it gets loaded by the command `using BlockBandedMatrices`. You are right, it does not get loaded as a direct dependency, but as a dependency of `FillArrays.jl`. Aqua cannot distinguish the two cases.

In https://github.com/JuliaArrays/FillArrays.jl/pull/286, `Statistics.jl` gets added as a weakdep of `FillArrays.jl`, and is thus no longer considered a dependency for julia versions 1.9+.
>Newer Julia versions will ignore dependencies in [deps] that are also in [weakdeps].
>(see https://pkgdocs.julialang.org/v1/creating-packages/#Transition-from-normal-dependency-to-extension)

Using this version of `FillArrays.jl`, neither `BlockBandedMatrices.jl` nor any of its dependencies loads `Statistics.jl`. Thus it is considered stale and makes the Aqua test fail.

So overall, there is no problem here, and everything is working as expected.

**Comment by jishnub** [comment]
> Aqua cannot distinguish the two cases

This should perhaps be clarified in the documentation

**Comment by lgoettgens** [comment]
> > Aqua cannot distinguish the two cases
> 
> This should perhaps be clarified in the documentation, although it does warn about stdlibs.

This does not only happen for stdlibs. I added some clarification in #164.
