### ISSUE TITLE
Stable docs out of date

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#181]
The stable docs on github pages (https://juliatesting.github.io/Aqua.jl/stable) refer to version v0.6.1, and there is no newer version other than `dev` available.

Maybe @fingolfin can have a look at this?

**Comment by lgoettgens** [comment]
As the last version in the docs is v0.6.1, this broke sometime between the v0.6.1 and the v0.6.2 releases. From looking through the commits, I think #118 by @fingolfin is the suspect.

**Comment by fingolfin** [comment]
The dev docs seem to be up-to-date, so there seems to be no problem with deploying things.

But looking at https://github.com/JuliaTesting/Aqua.jl/actions/workflows/docs.yml it seems that workflow is not being run on tags, as it should be. The .yml specifies that it should be run on all tags, though... 

A very similar setup works for AbstractAlgebra, see also https://github.com/Nemocas/AbstractAlgebra.jl/actions/workflows/CI.yml and there e.g. https://github.com/Nemocas/AbstractAlgebra.jl/actions/runs/6175946407

I do notice a minor issue with the TagBot setup, though... dunno if it could be responsible, I'll make a PR

**Comment by lgoettgens** [comment]
Solved by https://github.com/JuliaTesting/Aqua.jl/pull/184, backporting it to 0.6.x and making new releases.
