### ISSUE TITLE
Drop support for julia 1.0-1.3?

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#216]
https://github.com/JuliaTesting/Aqua.jl/pull/214 and thus https://github.com/JuliaTesting/Aqua.jl/pull/215 needed a workaround to circumvent an old problem in Pkg.jl in connection with Test.jl.
This would furthermore enable us to merge https://github.com/JuliaTesting/Aqua.jl/pull/195 eventually, thus removing a large code duplication with julia base.

> or we just drop support for older Julia versions in Aqua.jl ? I am not sure how valuable it is? After all, as was pointed out, people on older Aqua versions can still use the old Aqua releases. If they want any new features, well, they have to upgrade Julia.
There may be some people who absolutely must stick on Julia 1.0, but that's seems like a rather fringe demographic?
> -by @fingolfin on slack

I, personally, am in favor of this change. If somebody has some good reason why we should not proceed, please let me know.

**Comment by hyrodium** [comment]
I think we can also drop versions before v1.6 if we drop support for v1.0 because the other versions such as v1.4 are not LTS.

**Comment by fingolfin** [comment]
Also fine by me.

As it is, I wonder if it's worth bending over backwards if we don't even know whether anyone uses it...

One could of course also do something like this: the next release  prints a notice when loaded in Julia <= 1.3 (or 1.5) saying something like "if you'd like to receive updates for Aqua.jl in Julia $(VERSION) then please let us know at ISSUEURL". Then we wait a bit and see if someone reacts.

**Comment by lgoettgens** [comment]
> One could of course also do something like this: the next release prints a notice when loaded in Julia <= 1.3 (or 1.5) saying something like "if you'd like to receive updates for Aqua.jl in Julia $(VERSION) then please let us know at ISSUEURL". Then we wait a bit and see if someone reacts.

I don't know if many users look at ci logs when they succeed. And making the go red would be a breaking change. So no idea how to really do that
