### ISSUE TITLE
Rename `test_piracy` to `test_piracies`?

### ISSUE THREAD

**Issue by hyrodium** [JuliaTesting/Aqua.jl#228]
As I mentioned in https://github.com/JuliaTesting/Aqua.jl/pull/88#issuecomment-1783738175, I believe it would be more consistent to rename the `test_picary` function to `test_piracies`, similar to how we have `test_ambiguities`.

**Comment by lgoettgens** [comment]
I have no opinion on this.

But since this would be a breaking change, now (before the upcoming 0.8.0 release) would be a good time to do such a change.

**Comment by hyrodium** [comment]
Should we deprecate with `@deprecate test_piracy test_piracies` and release v0.7.5?
Or, can I make a PR to rename the function without deprecation?

**Comment by lgoettgens** [comment]
You can add a PR without deprecation to be released as part of 0.8.0 (if @fingolfin doesn't object)

**Comment by fingolfin** [comment]
I personally think this is pointless busywork, but as long as someone else does it and it doesn't cause me any extra work, I won't object :-)
