### ISSUE TITLE
Being able to get actionable output and issue details out of Aqua

### ISSUE THREAD

**Issue by goudrob83** [JuliaTesting/Aqua.jl#232]
Hello,

We from TIOBE software have developed a Code Quality framework in which many different Code Quality Metrics are being measured. As of recent we have added Julia support to our framework to measure some Code Quality Metrics for this new technology too.

On our customer request we are checking whether Aqua.jl tool qualifies as a proper Code Quality tool that can be integrated into our framework. We are aiming to have the tool used for the "Coding Standard" metric, as it's a tool that is able to inform the engineer on specific bad coding practices or code smells.

Together with Julia expert we tried to use your tool to get the right information out of it, but we are unable to do so. We would like to know about the following aspects. If some aspect is not covered, please consider this a Change Request to your tool:

1. Can the Aqua tool be run on a single Julia file and only get issues found/originating in that file? Or is the tool only working on a Julia project level?
2. We would like to get per issue at least the following information:
- File name where the issue is found
- Line number where the issue is found
- Violation message
- Which Aqua check triggered this issue
3. The information is to be returned in a parseable output
4. We want to run from the command line, outside of Julia context. Perhaps you can create a Julia file that checks all prerequisites and installs all prerequisites if not available, then run the tool provided the project (or file) and then return the violation information.
5. Is there a way to get from the tool the set of checks supported by the tool?

Please feel free to reach out to me on rob.goud@tiobe.com

Thanks,
Rob

**Comment by lgoettgens** [comment]
Hi Rob,

Overall, your request seems to be very similar to #108.
Aqua is, from the core design, only possible to be run from a julia environment with the to-test package already present. 
Some more concrete answers:

1. Only per project. Most of the conducted tests are not sensible to be checked only for single files, only for projects.
2. You already get all information there is. In some cases, some of the requested information is not sensible. EG the ambiguity check gives two sets of these per issue.
3. Related to #108 or #180
4. No that's not possible. If you want to check your code using a julia project, you NEED julia context. And as I stated initially, Aqua doesn't support that.
5. Please have a look at the documentation. There you can find a list.

**Comment by goudrob83** [comment]
Hi Lars,

Thanks for your prompt reply!


  1.  OK. Clear. Analysis is to be done on project level
  2.  We could not get such details on the original code out of the tool.

It would help if your documentation would include test cases and example output

  1.  Would it be hard for you to perorm such improvement? Of course we can also parse the output from stdout as long as the output is in a consistent way
  2.  Sure, Julia context is needed. But one could run "julia -e ….." right? That is what we are looking for
  3.  Yes, it's in the documentation, but over time you will be extending your tool. It's always best if your tool provides a way to summarize all the kinds of checks it can perform

Perhaps we can schedule a live session to go over the request and questions to tackle them?
We can update this ticket accordingly.

Thanks,
Rob

Van: Lars Göttgens ***@***.***>
Verzonden: Wednesday, 1 November 2023 09:29
Aan: JuliaTesting/Aqua.jl ***@***.***>
CC: Rob Goud ***@***.***>; Author ***@***.***>
Onderwerp: Re: [JuliaTesting/Aqua.jl] Being able to get actionable output and issue details out of Aqua (Issue #232)


Hi Rob,

Overall, your request seems to be very similar to #108<https://github.com/JuliaTesting/Aqua.jl/issues/108>.
Aqua is, from the core design, only possible to be run from a julia environment with the to-test package already present.
Some more concrete answers:

  1.  Only per project. Most of the conducted tests are not sensible to be checked only for single files, only for projects.
  2.  You already get all information there is. In some cases, some of the requested information is not sensible. EG the ambiguity check gives two sets of these per issue.
  3.  Related to #108<https://github.com/JuliaTesting/Aqua.jl/issues/108> or #180<https://github.com/JuliaTesting/Aqua.jl/issues/180>
  4.  No that's not possible. If you want to check your code using a julia project, you NEED julia context. And as I stated initially, Aqua doesn't support that.
  5.  Please have a look at the documentation. There you can find a list.

**Comment by fingolfin** [comment]
Point 2 and 3 seems to be closely tied to each other: we do *print* the information you ask for under 2 (so I am a bit surprised you "could not get such details"?), but indeed not in a machine readable way, so maybe that's what you meant?

I definitely agree that an (optional) machine readable output would be useful for all kinds of purposes; @lgoettgens already pointed at two related prior issues. If someone provides a PR, I'd happy to offer to review it. I might even work on that myself one day, but for now have other priorities besides my volunteer work on keeping this package alive, and I think it's similar for @lgoettgens.

If you have specific suggestions on the machine readable output, such as pointers to existing file formats for this kind of information, that certainly could be useful; perhaps you could add that information as a comment on #108?


Your question/request 5 resp. your expectations for it similarly only make sense to me in context of your question/request 4. Request 5 still seems rather subjective to me, though? You wrote
> It's always best if your tool provides a way to summarize all the kinds of checks it can perform

I could counter by saying
> It's always best if your tool has documentation that summarizes all the kinds of checks it can perform.

I see no reason why one should be superior to the other? If you do, please let's hear it! Note that the argument "this is how other tools TIOBE works with do it and it would be convenient for our use case"  may be valid for you, but is not of intrinsic relevance to us. Anyway, I wouldn't object to a PR related to this.


For some context, the intended way to use Aqua is either from the Julia REPL (for experiments) or from Julia CI tests (to ensure code changes do not introduce a code breakage). In the former setting, one can just use the Julia help system, by entering `?Aqua`, to get an overview.


Regarding point 4 specifically, you also wrote:
> Perhaps you can create a Julia file that checks all prerequisites and installs all prerequisites if not available.

I see no fundamental obstacle to this, but personally I have no need for this and see no serious benefit, so I won't work on it. 

No offense, but: If you are interested in having this, I would expect that it is no problem for a for-profit company like TIOBE, which apparently wants this to satisfy a request by one of your customers, to get someone to implement it? As a starter you could look into how existing GitHub Workflows integrate Julia tests which in turn is usually how Aqua is called from typical Julia packages. Those indeed include some `julia -e SOMETHING` invocations to create new project environments, adding packages, and invoking some "test" function in there.
