### ISSUE TITLE
Documentation not available on github pages

### ISSUE THREAD

**Issue by lgoettgens** [JuliaTesting/Aqua.jl#247]
0816b05f0567b76322d195510d5ffe40885b064b was the last commit that the github pages deployment ran on.
Starting with a1743e32d7a17f3cae35f64ddcbf0184b3cf96cd, the pages environment throws a 404 (see https://juliatesting.github.io/Aqua.jl/).

@fingolfin could you please check the project settings and maybe disable and re-enable github pages there? Hopefully that fixes it.
(And maybe protect the gh-pages branch a bit. Commiting and everything is fine, but I think force-pushing and deleting it and so on shouldn't be allowed.)

**Comment by LilithHafner** [comment]
Bump.
<img width="812" alt="Screenshot 2023-11-19 at 8 04 12 PM" src="https://github.com/JuliaTesting/Aqua.jl/assets/60898866/1351d6d5-b581-48a8-8899-4728d5148996">
The second and third google search results for "Aqua.jl" give 404 errors.

**Comment by fingolfin** [comment]
Just preventing force pushes will only break things more as long as the GH workflows are configured to use them. 

Which is actually a normal thing to do qhen enabling PR doc previews because otherwise the repository size will spiral out of control. (The doc cleanup PR you added will do nothing about that, `git rm` alone will never shrink the tepo size).


Anyway, what actually happened to break the pages, do you know?

**Comment by lgoettgens** [comment]
> Just preventing force pushes will only break things more as long as the GH workflows are configured to use them.

True... 

> Which is actually a normal thing to do qhen enabling PR doc previews because otherwise the repository size will spiral out of control. (The doc cleanup PR you added will do nothing about that, `git rm` alone will never shrink the tepo size).

I copied the one from OSCAR without thinking about it. I should probably just copy the example from the Documenter docs all together. 

> Anyway, what actually happened to break the pages, do you know?

When installing the action and trying it, I got very confused with branches. And thus, by accident, deleted the origin/gh-pages pages branch. I re-pushed my local one immediately after, but github does not pick it up anymore.

**Comment by lgoettgens** [comment]
Thanks @fingolfin!
