### ISSUE TITLE
Possible unbound type parameter false positive

### ISSUE THREAD

**Issue by densmojd** [JuliaTesting/Aqua.jl#295]
I'm attempting to concatenate a tuple of SVector into an SMatrix, and I'm getting a unbound type parameter error I can't fix. Here's an MWE (here I just use a matrix comprehension to make things simple):
```
function cat_svector(v::NTuple{M, SVector{N, Float64}}) where {N, M}

    return [v[j][i] for i in 1:N, j in 1:M]

end
# special case for when no arguments are provided
cat_svector() = error("no arguments provided")
```
The special case was attempt to avoid unbound type parameters when no arguments are provided, but that didn't fix the problem.

**Comment by lgoettgens** [comment]
I think this is a duplicate of https://github.com/JuliaTesting/Aqua.jl/issues/86.

**Comment by densmojd** [comment]
FWIW, I still get the error if I remove `cat_svector()`.
