### ISSUE TITLE
add jldoctest as an optional check

### ISSUE THREAD

**Issue by johnnychen94** [JuliaTesting/Aqua.jl#40]
It would be convenient to also integrate jldoctest checks in Auqa

```Julia
using Documenter
DocMeta.setdocmeta!(ImageCore, :DocTestSetup, :(using ImageCore); recursive=true)
doctest(ImageCore, manual = false)
```

`Documenter` isn't something lightweight, though...

**Comment by tkf** [comment]
Do you mind elaborating on the motivation for calling `doctest` via Aqua.jl?  I think `doctest` is already a simple API to use.  Also, I usually need to guard `doctest` behind some `if` blocks checking `VERSION` and/or `ENV["JULIA_PKGEVAL"]`. I think calling `doctest` via Aqua.jl makes this kind of configurations hard.

**Comment by johnnychen94** [comment]
It occurs to me that Aqua covers some meta test for packages regardless of their contents. Doctest is one such test and that's why I propose this; only for conceptually completeness.

> Also, I usually need to guard doctest behind some if blocks checking VERSION and/or ENV["JULIA_PKGEVAL"]. I think calling doctest via Aqua.jl makes this kind of configurations hard.

Yes, this is a good reason not to do so. Most of the time, we might not have that amount of time to maintain a doctest for older Julia versions.

**Comment by tkf** [comment]
Thanks for the explanation. While I kind of get the "meta tests" argument, all the tests provided in Aqua.jl are rather tedious to set up.  OTOH, `doctest` already is very easy to set up.  So, I think it's better to just call `doctest` for now.  I think a better place for this kind of automation is PkgTemplates.jl.

Anyway, thanks for your interest in Aqua.jl!
