### ISSUE TITLE
Test docs project for missing compat?

### ISSUE THREAD

**Issue by ericphanson** [JuliaTesting/Aqua.jl#51]
It would be great if Aqua could test other Project.toml's for missing compat entries such as the one in the docs folder. That is a slightly tricky case since PkgX/docs likely has PkgX as a dep but does not want a compat bound for PkgX, but does want compat for all other dependencies.

**Comment by ericphanson** [comment]
On second thought, I think CompatHelper.jl will propose compat bounds for all Project's in a repo though, so this isn't actually super important if you also use CompatHelper, since you'll get PRs to fix it from that. It is nicer though to get the error in the PR that lacks the compat bound (from a hypothetical Aqua release that handles docs projects) rather than to get a fixup PR later.

**Comment by DilumAluthge** [comment]
> On second thought, I think CompatHelper.jl will propose compat bounds for all Project's in a repo though, so this isn't actually super important if you also use CompatHelper, since you'll get PRs to fix it from that.

Just FYI, this is not true. CompatHelper will only offer to add `[compat]` entries to the main `/Project.toml` in the root of the package.

CompatHelper will offer to update all _manifests_ in a package. But it won't modify any `Project.toml` file except the main `/Project.toml` file in the root of the package.
