### ISSUE TITLE
specify argument for test_stale_deps from test_all

### ISSUE THREAD

**Issue by dpinol** [JuliaTesting/Aqua.jl#53]
When executing test_all, I get 
`To ignore from stale dependency detection, pass the package name to `ignore` keyword argument of `Aqua.test_stale_deps`
but I don't know how to specify ignore argument to test_stale_deps  from test_all

thanks

**Comment by tkf** [comment]
I think  something like `test_all(TestTarget; stale_deps = (; stale_deps = [:PackageName])` should work.

**Comment by dpinol** [comment]
yes! just replacing the 2nd `stale_deps` with `ignore` it works
`test_all(TestTarget; stale_deps = (; **ignore**= [:PackageName])`

domo arigato gozaimasu
