### ISSUE TITLE
0.5 is not released

### ISSUE THREAD

**Issue by Roger-luo** [JuliaTesting/Aqua.jl#54]
not sure why, but it seems v0.5 was not released by TagBot, maybe should update the TagBot GA?

**Comment by tkf** [comment]
I think it was released? https://github.com/JuliaTesting/Aqua.jl/releases/tag/v0.5.0

Maybe you were looking at the front page of GitHub? It's showing 0.4.11 because I released 0.4.11 after 0.5, I think.

**Comment by Roger-luo** [comment]
ah I see thanks for clarification
