### ISSUE TITLE
`test_all` that doesn't fail fast

### ISSUE THREAD

**Issue by anandijain** [JuliaTesting/Aqua.jl#56]
it'd be awesome to get like a report of errors rather than have to loop through `test_all, fix, test_all, fix...` 

because some of the issues are going to be more important than others so id like to just scroll through and see them all at once.

if this is too much effort then please ignore

**Comment by anandijain** [comment]
particularly because it doesn't seem to work with Revise, so I have to close REPL and rerun

**Comment by tkf** [comment]
I think you can do non-fail fast with

```julia
using  Aqua, Test
@testset begin
    Aqua.test_all(Package)
end
```

**Comment by anandijain** [comment]
thanks
