### ISSUE TITLE
Printing at `__init__` time throws off stale dependencies check

### ISSUE THREAD

**Issue by ericphanson** [JuliaTesting/Aqua.jl#60]
Specifically, https://github.com/JuliaTesting/Aqua.jl/blob/9eff6edf048720f0d32900bc30730570e31e305e/src/stale_deps.jl#L57

throws. Generally printing during `__init__` isn't good practice since downstream packages will print when they load, but it can be helpful for leaf packages (i.e. applications).

**Comment by tkf** [comment]
Yeah, the current implementation is rather sloppy. I guess probably the best strategy is to create a temporary file and log UUIDs in it.
