### ISSUE TITLE
Aqua considers itself a stale dependency

### ISSUE THREAD

**Issue by baggepinnen** [JuliaTesting/Aqua.jl#78]
The readme suggests adding Aqua to the `[deps]` section of Project.toml, but doing so causes Aqua to complain that Aqua is not loaded and is considered a stale dependency:
```julia
Test Failed at /home/fredrikb/.julia/packages/Aqua/HWLbM/src/stale_deps.jl:24
  Expression: result ⊜ true
   Evaluated: ⟪result: 😭 FAILED: ControlSystems 
    Some package(s) in `deps` of ControlSystems are not loaded during via `using ControlSystems`.
    * Aqua [4c88cf16-eb10-579e-8560-4a9242c79595]
```
I don't want to load Aqua in the package, it should be a test only dependency, and I don't want to turn off detection of stale dependencies. A reasonable approach would perhaps be for Aqua to be self aware and filter itself out as a stale dependency?

**Comment by DilumAluthge** [comment]
Aqua should not be in deps. I think we just need to fix the README.

Aqua can be in extras and the test target, which allows you to set compat bounds on Aqua.

**Comment by fingolfin** [comment]
There is no bug here, good.

The suggestion for enhancing the documentation is now in issue #123
