### ISSUE TITLE
Something is broken in piracy check

### ISSUE THREAD

**Issue by bvdmitri** [JuliaTesting/Aqua.jl#95]
We have recently started to get the following error in our CI (previously everything was OK): 

https://github.com/biaslab/ReactiveMP.jl/actions/runs/3929126548/jobs/6717570554

This error suggests that some code in Aqua.jl does not work well for the following definition:
```julia
Base.nameof(::Type{T}) where {N, R, V <: NTuple{N, <:R}, T <: ManyOf{V}} = string("ManyOf{", N, ", ", nameof(dropproxytype(R)), "}")
```

There is no type-piracy, because the type `T` explicitly set to be of type `ManyOf`, which is defined in our package. The error says that `N` is not defined, but it is defined in the code and this function also executes fine without any errors. That makes me think that type-piracy logic in Aqua is incomplete, but I do not understand the implementation and I'm not quite sure where the issue is.

**Comment by Seelengrab** [comment]
> The error says that N is not defined

My guess is that it's due to `V` not being concretely inferred at the poing of where this is called, leading to `N` not being uniquely defined (i.e. it only has `V <: NTuple{N, X} where N` for some concrete `X` to work with)

**Comment by bvdmitri** [comment]
I see, thanks for the explanation. I think we can also rename the function to something else such that it is not overriding the default behaviour.

**Comment by fingolfin** [comment]
Thank you all for the report and the subsequent discussion and analysis.

I believe this issue was address upstream by not overriding `Base.nameof`, so I am now going to close it.
