### ISSUE TITLE
Allow type piracy from superpackage?

### ISSUE THREAD

**Issue by kshyatt** [JuliaTesting/Aqua.jl#96]
Suppose I have two packages `A` and `B`, and `B` is a subpackage of `A` (they live in the same repo), perhaps to provide additional, optional functionality (e.g. GPU integration). In such a case, I might actually want `B` to engage in some type piracy from `A` - is there a way to allow that in the `Aqua` checks for `B`?

**Comment by jakobnissen** [comment]
Not yet, but this would be a good idea. Perhaps to provide a set of packages from which your package is allowed to pirate.
